spin_version = "1"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = ""
name = "devctest2"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "devctest2"
source = "target/wasm32-wasi/release/devctest2.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
